export const motsClefs = [
  "Ingénierie",
  "Calcul",
  "Simulation",
  "Développement logiciel",
  "Conseils",
  "Éléments finis",
  "Conception",
  "Numérique",
  "Naval",
  "Spatial",
  "Aéronautique",
  "Défense",
  "Énergie",
  "Transport",
]
